[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs-permissions = [{access = "read-write", path = "./"}]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink-local/=lib/chainlink-local/",
    "forge-std/=lib/forge-std/src",
    "murky/=lib/murky",

]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
